version: "3.8"

services:
  client:
    image: node:lts
    container_name: revo-client
    working_dir: /app/App
    volumes:
      - ./client:/app/App
      - /app/App/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    command: bash -c "npm i && npm run dev"

  server:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: revo-server
    working_dir: /app/App
    volumes:
      - $HOME/.vsdbg:/root/.vsdbg
      - $HOME/.vsdbg/linux-x64/latest:/remote_debugger/linux-x64/latest
      - /app/App/obj/
      - /app/App/bin/
      - ./server/src/App:/app/App
    ports:
      - 5000:5000
    depends_on:
      psql:
        condition: service_started
      redis:
        condition: service_started
    command: dotnet watch run --urls http://0.0.0.0:5000 --non-interactive

  psql:
    container_name: revo-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=revo
      - POSTGRES_PASSWORD=revo
      - POSTGRES_DB=revo
    ports:
      - 5432:5432
    volumes:
      - revo_db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: revo-redis
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping | grep PONG
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  default:
    name: revo
volumes:
  revo_db:
